name: Release
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - '*'
env:
  REGISTRY: ghcr.io
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
